---
# tasks file for redis

- include_tasks: install.yml
  when: cmd == "start"

- include_tasks: sentinel.yml

- include_tasks: master.yml
  vars:
    service: "{{item}}"
  with_items: 
    - event
    - alarm
