---

- include_vars: "{{ service }}_server.yml"

- name: configure {{ service }} master
  template:
    src: master.conf.j2
    dest: ./{{service}}_master.conf
  when: cmd == "start"

- name: start {{ service }} server
  vars:
    log_file: "{{service}}_log_file"
  shell: nohup redis-server ./{{service}}_master.conf > {{ log_file }} 2>&1 &
  when: cmd == "start"

- include_tasks: stop.yml
  vars:
    port: "{{ master_port }}"
    pid_file: "{{master_pid_file}}"
  when: cmd == "stop"
