---
- include_vars: sentinel.yml

- name: configure sentinel
  template:
    src: sentinel.conf.j2
    dest: ./sentinel.conf
  when: cmd == "start"

- name: start sentinel
  shell: nohup redis-sentinel ./sentinel.conf > "{{ sentinel_log_file }}" 2>&1 &
  when: cmd == "start"

- include_tasks: stop.yml
  vars:
    service: sentinel
    port: "{{sentinel_port}}"
    pid_file: "{{sentinel_pid_file}}"
  when: cmd == "stop"