---
- include_vars: sentinel.yml

- name: configure sentinel
  template:
    src: sentinel.conf.j2
    dest: ./sentinel.conf
  when: cmd == "start"

- name: start sentinel
  shell: nohup redis-sentinel ./sentinel.conf > "{{ sentinel_log_file }}" 2>&1 &
  when: cmd == "start"

- name: stop sentinel
  shell: redis-cli -p {{sentinel_port}} shutdown
  when: cmd == "stop"

- name: remove sentinel pid file
  file:
    path: "{{sentinel_pid_file}}"
    state: absent
  when: cmd == "stop"
